[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.2", features = [ "runtime-tokio", "tls-native-tls", "sqlite" ] }
tokio = { version = "1.40.0", features = ["macros"]}

[profile.dev.package.sqlx-macros]
opt-level = 3